# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m1TAINR3T8cEsM1nIRJvsui1BmF_bB5w
"""

import streamlit as st
import pandas as pd
import joblib

# Load dataset dan model
url = "https://raw.githubusercontent.com/rendymalandi/last-pliss/main/Heart_Disease_Prediction.csv"
df = pd.read_csv(url)
model = joblib.load("heart_disease_model.pkl")

# Sidebar navigasi
st.sidebar.title("Navigasi")
page = st.sidebar.radio("Pilih Halaman", ["Dataset", "Modeling", "Prediksi"])

# Halaman 1 - Dataset
if page == "Dataset":
    st.title("📊 Dataset Penyakit Jantung")
    st.write("Berikut adalah cuplikan data yang digunakan:")
    st.dataframe(df.head())

    st.subheader("Informasi Dataset:")
    st.write(df.describe())

    st.subheader("Distribusi Target:")
    st.bar_chart(df['HeartDisease'].value_counts())

# Halaman 2 - Modeling
elif page == "Modeling":
    st.title("🧠 Evaluasi Model")
    st.write("Model ini telah dilatih sebelumnya menggunakan algoritma machine learning.")
    st.markdown("- 📁 Model: `heart_disease_model.pkl`")
    st.markdown("- ✅ Fitur: Berdasarkan data pasien (usia, tekanan darah, kolesterol, dll)")

    st.info("Kamu dapat menampilkan akurasi, classification report, atau confusion matrix jika model menyimpannya sebagai pipeline dengan `.score()` atau `predict()` di training data.")

    # Tambahan jika kamu punya data metrik
    try:
        from sklearn.metrics import classification_report
        X = df.drop("HeartDisease", axis=1)
        y = df["HeartDisease"]
        y_pred = model.predict(X)
        report = classification_report(y, y_pred, output_dict=True)
        st.write("**Classification Report**:")
        st.json(report)
    except:
        st.warning("Gagal menghitung metrik, pastikan model berbentuk pipeline dan data sudah diolah.")

# Halaman 3 - Prediksi
elif page == "Prediksi":
    st.title("🩺 Prediksi Penyakit Jantung")

    # Form input
    age = st.number_input("Usia", min_value=1, max_value=120, value=30)
    sex = st.selectbox("Jenis Kelamin", ["Male", "Female"])
    chest_pain = st.selectbox("Tipe Nyeri Dada", ["TA", "ATA", "NAP", "ASY"])
    resting_bp = st.number_input("Tekanan Darah Saat Istirahat", min_value=0, value=120)
    cholesterol = st.number_input("Kolesterol", min_value=0, value=200)
    fasting_bs = st.selectbox("Gula Darah Puasa > 120 mg/dl", [0, 1])
    resting_ecg = st.selectbox("Elektrokardiografi Saat Istirahat", ["Normal", "ST", "LVH"])
    max_hr = st.number_input("Detak Jantung Maksimum", min_value=0, value=150)
    exercise_angina = st.selectbox("Angina karena Latihan?", ["Y", "N"])
    oldpeak = st.number_input("Oldpeak (ST Depression)", value=1.0)
    st_slope = st.selectbox("Kemiringan ST", ["Up", "Flat", "Down"])

    # Prediksi
    if st.button("Prediksi"):
        input_df = pd.DataFrame({
            "Age": [age],
            "Sex": [sex],
            "ChestPainType": [chest_pain],
            "RestingBP": [resting_bp],
            "Cholesterol": [cholesterol],
            "FastingBS": [fasting_bs],
            "RestingECG": [resting_ecg],
            "MaxHR": [max_hr],
            "ExerciseAngina": [exercise_angina],
            "Oldpeak": [oldpeak],
            "ST_Slope": [st_slope]
        })

        result = model.predict(input_df)[0]
        if result == 1:
            st.error("⚠️ Pasien berisiko mengalami penyakit jantung.")
        else:
            st.success("✅ Pasien tidak berisiko mengalami penyakit jantung.")